coverage:
  status:
    project:
      default:
        target: 80%    # the required coverage value
        threshold: 0.01%  # the leniency in hitting the target
  ignore:
  - "src/**/visualization/**/*"
  - "src/models/differentiable/R/rtorch_model.jl"