flowchart TB
    
    classDef module fill:#cb3c33,stroke:#333,color:#fff,stroke-width:4px;
    classDef struct fill:#389826,stroke:#333,color:#fff;
    classDef funct fill:#9558b2,stroke:#333,color:#fff;
    %% classDef default font-size:36px,height:60px;

    %% Components
    data(["Data"])
    generative(["GenerativeModels"])
    vae["AbstractGenerativeModel"]
    data_pre(["DataPreprocessing"])
    c_data["CounterfactualData"]
    models(["Models"])
    model["AbstractFittedModel"]
    generators(["Generators"])
    generator["AbstractGenerator"]
    generate_counterfactual{{"generate_counterfactual"}}
    ce["CounterfactualExplanation"]
    eval(["Evaluation"])
    obj(["Objectives"])

    class vae,c_data,model,generator,ce struct;
    class data,generative,data_pre,models,generators,eval,obj module;
    class generate_counterfactual funct;

    %% Graph
    data --> data_pre
    data_pre --o c_data
    c_data --> generative 
    generative --o vae
    vae ---> c_data

    models ---o model

    obj --> generators
    generators --o generator

    c_data & model & generator --> generate_counterfactual

    generate_counterfactual --o ce

    ce --> eval