```{r}
library(kableExtra)
library(data.table)
generators <- c(
    "ClaPROAR \\cite{altmeyer2023endogenous}",
    "CLUE \\cite{antoran2020getting}",
    "DiCE \\cite{mothilal2020explaining}",
    "FeatureTweak \\cite{tolomei2017interpretable}",
    "Gravitational \\cite{altmeyer2023endogenous}",
    "Greedy \\cite{schut2021generating}",
    "GrowingSpheres \\cite{laugel2017inversea}",
    "PROBE \\cite{pawelczyk2022probabilistically}",
    "REVISE \\cite{joshi2019realistic}",
    "Wachter \\cite{wachter2017counterfactual}"
)
models <- c(
    "gradient based",
    "gradient based",
    "gradient based",
    "tree based",
    "gradient based",
    "gradient based",
    "agnostic",
    "gradient based",
    "gradient based",
    "gradient based"
)
search_space <- c(
    "feature",
    "latent",
    "feature",
    "feature",
    "feature",
    "feature",
    "feature",
    "feature",
    "latent",
    "feature"
)
composable <- c(
    "yes",
    "yes",
    "yes",
    "no",
    "yes",
    "yes",
    "no",
    "no",
    "yes",
    "yes"
)
tab <- data.table(generators,models,search_space,composable)
```

```{r}
col_names <- c("Generator", "Model Type", "Search Space", "Composable")
caption <- "Overview of implemented counterfactual generators. \\label{tab-gen} \\newline"
kbl(
  tab, caption = caption, col.names=col_names, booktabs = T, escape=F, 
  format="latex", linesep = ""
) %>%
  kable_styling(font_size = 7) %>%
  kable_paper(full_width = F) 
```