name: Format Check

on:
  push:
    branches:
      - 'main'
      - 'release-'
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1
      - uses: actions/checkout@v1
      - name: Install JuliaFormatter
        run: |
          using Pkg
          Pkg.add("JuliaFormatter")
        shell: julia --color=yes {0}
      - name: Format code
        run: |
          using JuliaFormatter
          format("."; verbose=true)
        shell: julia --color=yes {0}